# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "A Glass of Lores"
description: > # this means to ignore newlines until "email:"
   A new top down RPG game that you will be able to play right on this webpage.

email: elhafulvics@gmail.com
#blog logo
logo: "/assets/images/agol_logo.jpg"
# blog cover
cover: "/assets/images/titleimgsw.jpg"

name: 'Erico Porto'
author: 'Erico Porto'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://ericoporto.github.io/fangamk" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/aglassoflores
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/ericoporto
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
